const { createClient } = require('@supabase/supabase-js');
const { Resend } = require('resend');

const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);
const resend = new Resend(process.env.RESEND_API_KEY);

module.exports.config = { api: { bodyParser: false } };

module.exports = async (req, res) => {
  if (req.method !== 'GET') {
    return res.status(405).end('Method Not Allowed');
  }

  const { session_id, token } = req.query || {};

  // Validate token
  if (!token || token !== process.env.REVIEW_SECRET) {
    return res.status(401).send('<h2>Unauthorised</h2><p>Invalid or missing review token.</p>');
  }

  if (!session_id) {
    return res.status(400).send('<h2>Bad Request</h2><p>Missing session_id.</p>');
  }

  // Fetch order from Supabase
  const { data: order, error: fetchError } = await supabase
    .from('orders')
    .select('*')
    .eq('stripe_session_id', session_id)
    .single();

  if (fetchError || !order) {
    console.error('Order not found:', fetchError);
    return res.status(404).send('<h2>Not Found</h2><p>Order not found for session: ' + session_id + '</p>');
  }

  if (order.status === 'report_sent') {
    return res.status(200).send([
      '<!DOCTYPE html><html><head><meta charset="utf-8"><title>Already Sent</title></head><body style="font-family:Arial;padding:40px;max-width:600px;margin:0 auto;">',
      '<h2 style="color:#27ae60;">Already Sent</h2>',
      '<p>This report has already been sent to <strong>' + order.customer_email + '</strong>.</p>',
      '<p style="color:#666;font-size:0.9rem;">Session: ' + session_id + '</p>',
      '</body></html>'
    ].join(''));
  }

  if (!order.report_html) {
    return res.status(400).send('<h2>Error</h2><p>No report HTML found for this order. Report may not have been generated yet.</p>');
  }

  // Build allFindings stub for email (we just need counts from order metadata)
  const allFindings = [];

  // Send the report to the client
  const pkgLabel = { essential: 'Essential Review', complete: 'Complete Analysis', premium: 'Premium Report' }[order.package_type] || order.package_type;

  const clientHtml = [
    '<!DOCTYPE html><html><head><meta charset="utf-8"><style>',
    'body{font-family:Arial,sans-serif;line-height:1.6;color:#333;margin:0;padding:0}',
    '.hdr{background:#1a3c5e;color:white;padding:24px;text-align:center}',
    '.cnt{padding:30px;max-width:700px;margin:0 auto}',
    '.rpt{background:#fafafa;border:1px solid #e0e0e0;border-radius:8px;padding:24px;margin:20px 0}',
    '.ftr{background:#f8f9fa;padding:20px;text-align:center;font-size:13px;color:#666}',
    'h3{color:#1a3c5e;border-bottom:2px solid #e3f2fd;padding-bottom:6px}',
    '</style></head><body>',
    '<div class="hdr">',
    '<h1 style="margin:0">Verihome NZ</h1>',
    '<h2 style="margin:8px 0 0;font-weight:normal;opacity:0.9">' + pkgLabel + ' &mdash; Property Analysis Report</h2>',
    '</div>',
    '<div class="cnt">',
    '<p>Dear <strong>' + (order.customer_name || 'Valued Customer') + '</strong>,</p>',
    '<p>Your property document analysis is complete. Here is your full report:</p>',
    order.property_address ? '<p><strong>Property:</strong> ' + order.property_address + '</p>' : '',
    '<div class="rpt">' + order.report_html + '</div>',
    '<div style="background:#fff8e1;padding:16px;border-left:4px solid #ffc107;border-radius:4px;font-size:13px;margin:20px 0">',
    '<strong>Legal Disclaimer:</strong> This report is generated by an AI-assisted analysis system for informational purposes only. It does not constitute legal advice. Verihome NZ and Protocol Zero Limited recommend consulting a qualified New Zealand solicitor for all significant property transactions.',
    '</div>',
    '<p>Questions? Contact us at <a href="mailto:support@verihome.co.nz">support@verihome.co.nz</a></p>',
    '<p>Best regards,<br><strong>The Verihome NZ Legal Analysis Team</strong></p>',
    '</div>',
    '<div class="ftr"><p>Protocol Zero Limited &middot; Verihome NZ &middot; AI-Powered NZ Property Document Analysis<br>',
    'This email contains confidential analysis prepared for the named recipient only.</p></div>',
    '</body></html>'
  ].join('\n');

  const { error: sendError } = await resend.emails.send({
    from: 'Verihome NZ <support@verihome.co.nz>',
    to: order.customer_email,
    subject: 'Your Verihome Property Report is Ready &mdash; ' + pkgLabel,
    html: clientHtml,
  });

  if (sendError) {
    console.error('Failed to send report:', sendError);
    return res.status(500).send('<h2>Error</h2><p>Failed to send email: ' + sendError.message + '</p>');
  }

  // Update order status
  await supabase
    .from('orders')
    .update({ status: 'report_sent' })
    .eq('stripe_session_id', session_id);

  console.log('Report approved and sent to:', order.customer_email);

  // Return success page
  return res.status(200).send([
    '<!DOCTYPE html><html><head><meta charset="utf-8"><title>Report Sent</title></head>',
    '<body style="font-family:Arial;padding:60px 40px;max-width:600px;margin:0 auto;text-align:center;">',
    '<div style="font-size:4rem;margin-bottom:1rem;">&#9989;</div>',
    '<h1 style="color:#27ae60;margin-bottom:0.5rem;">Report Sent!</h1>',
    '<p style="font-size:1.1rem;color:#333;">The report has been sent to:</p>',
    '<p style="font-size:1.2rem;font-weight:700;color:#1a3c5e;">' + order.customer_email + '</p>',
    '<div style="background:#f8f9fa;border-radius:8px;padding:16px;margin:24px 0;text-align:left;font-size:0.9rem;">',
    '<strong>Client:</strong> ' + (order.customer_name || 'N/A') + '<br>',
    '<strong>Package:</strong> ' + pkgLabel + '<br>',
    '<strong>Property:</strong> ' + (order.property_address || 'N/A') + '<br>',
    '<strong>Session:</strong> ' + session_id,
    '</div>',
    '</body></html>'
  ].join(''));
};
